### ISSUE TITLE
Bot wont deploy after starting

### ISSUE THREAD

**Issue by H-Fizzle** [TannerGabriel/discord-bot#237]
**Describe the bug**
i built the bot using the docker file and after the container starts,
when im trying to deploy the bot using the (!deploy) comand, the bot never deploys or responds in any way.
 

**To Reproduce**
1. build docker file
2. run docker container
3. add bot to a server
4. run the !deploy comand

**Expected behavior**
the expected behavior would be the bot replying with a conformation that it had been deployed,
and the slash comands showing up in the text chat

**Desktop (please complete the following information):**
 - OS: Debian 11
 - CPU x86 

**Dependency versions:**
 - Nodejs version:12.22.12
 - YTDL-core version:

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by TannerGabriel** [comment]
I accidentally removed some needed intents. #238 should fix the problem. Please try it out and tell me if it works.

**Comment by H-Fizzle** [comment]
i re-cloned the repo and built the docker file again and it still seams to not work.
it runs sucsessfuly and appears online on discord, but sadly it still does not reply to !deploy comands

**Comment by smclean117** [comment]
Double check on the discord developer portal that your bot has the required permissions, such as  “messages intent” enabled.

**Comment by H-Fizzle** [comment]
yep its checked, i just enabled everything appart from "REQUIRES OAUTH2 CODE GRANT" and still nothing

**Comment by smclean117** [comment]
It could even be that the text channel you're typing in, the bot may not have permission to read, some server side role conflict?

You could try re-inviting the bot with administrator privileges temporarily to see if this is the case.

**Comment by H-Fizzle** [comment]
ive tried this by just giving the bot admin permissions and in a brand new empty server,
and yet still nothing, it semes as though the bot just cant see the mesage but im not sure why

**Comment by smclean117** [comment]
I'm also a bit stumped by this, you have ticked the application.commands box next to the bot box when generating its invite link?

![image](https://github.com/TannerGabriel/discord-bot/assets/90870055/e39b8614-011c-40d7-873d-e0f614ef5e07)

**Comment by H-Fizzle** [comment]
yep i checked both boxes and checked the administrator box, 
then used the link to add it to the server, and nothing.

im not sure as to what is causing it, ive never had this issue in the past with previous versions

**Comment by TannerGabriel** [comment]
> i re-cloned the repo and built the docker file again and it still seams to not work. it runs sucsessfuly and appears online on discord, but sadly it still does not reply to !deploy comands

Did you switch to the branch in the PR? The master branch does not have the changes yet. I tried it out yesterday and it seemed to be working again.

**Comment by TannerGabriel** [comment]
I merged the PR after making sure that it worked on my site. You can now test the changes on `master`.

**Comment by cgwhouse** [comment]
@TannerGabriel thank you so much for your continued efforts in maintaining this project! Can confirm after getting latest `master` that this fix worked for me.

For my own curiosity, may I ask which major version of Node you use when you run the bot for yourself? I have used both 16.x and 18.x with success, and I know the README just says 16 or higher, but wanted to know what you personally use / prefer? Assuming the answer is 18 based on the Dockerfile?

**Comment by TannerGabriel** [comment]
Thank you for testing. I will close the issue since it seems to be fixed. If you are still experiencing problems, let me know and I will reopen it again.

Regarding node versions, I prefer using 18.x for most of my personal projects as it feels stable and functions well according to my needs. However, certain projects I collaborate on or work with still require 16.x or perform better with it.
